#!/bin/bash

cr=''
down='B'
over='&a[0-9]*C'
tab='	'
spc=' '
lf='\
'

top -d1 -n5 \
		| tr "$cr" "$lf" \
		| sed -e "s/$cr$down/$lf/g" \
			  -e "s/$down/$lf/g" \
			  -e "s/$over/$tab/g" \
		| tr -s "$spc" "$tab" \
		> junk

sleep 5
vi junk
