#!/bin/bash

# Set up the FPA environment
. .fpaenvrc

# Determine the platform
export PLATFORM;	PLATFORM=`$FPA/bin/platform`
echo "FPA User Input Makefile Utility"
echo "  Target Platform:   $PLATFORM"
echo "  Working Directory: `pwd`"
echo "  Log File:          `pwd`/log"
echo

MAKEFILE=Makefile.input
if [ ! -r $MAKEFILE ]
then
	echo "Cannot access $MAKEFILE"
	exit 1
fi

# Set up the platform-specific environment
case $PLATFORM in

	# 64-bit HP platforms:
	hppa2*10 | hppa2*11)
			MAKE="/bin/make -f $MAKEFILE"
			SHLIB_EXT=sl
			C_COMPILER="/opt/ansic/bin/cc -Aa +DA2.0 +DS2.0 -DMACHINE_HP"
			C_COMPLOAD="${C_COMPILER} -Wl,+s -Wl,-E -Wl,-Z"
			C_COMP_SHARED="${C_COMPILER} +z"
			C_OPTIONS="-g"
			LIB_ARCHIVE="/usr/ccs/bin/ar cr"
			LIB_ORDER="/usr/ccs/bin/lorder"
			LIB_SORT="/usr/ccs/bin/tsort"
			LIB_SHARED="/usr/ccs/bin/ld -b -E +s"
			LIB_NAMES="/usr/ccs/bin/nm"
			LOADER="/bin/ld -E +s -Z"
			LIB_PATH=""
			INCLUDE_PATH="-D_HPUX_SOURCE -DSYSV -Dhpux"
			EXTRA_FTN_LIBS=
			EXTRA_LIBS="-lcl -lm"
			;;


	# 32-bit HP platforms:
	hppa1*10 | hp700*10)
			MAKE="/bin/make -f $MAKEFILE"
			SHLIB_EXT=sl
			C_COMPILER="/opt/ansic/bin/cc -Aa +DAportable -DMACHINE_HP"
			C_COMPLOAD="${C_COMPILER} -Wl,+s -Wl,-E -Wl,-Z"
			C_COMP_SHARED="${C_COMPILER} +z"
			C_OPTIONS="-g"
			FTN_COMPILER="/opt/fortran/bin/f77"
			FTN_COMPLOAD="${FTN_COMPILER} -Wl,+s"
			FTN_COMP_SHARED="${FTN_COMPILER}"
			LEX="/opt/langtools/bin/lex"
			LIB_ARCHIVE="/usr/ccs/bin/ar cr"
			LIB_ORDER="/usr/ccs/bin/lorder"
			LIB_SORT="/usr/ccs/bin/tsort"
			LIB_SHARED="/usr/ccs/bin/ld -b -E +s"
			LIB_NAMES="/usr/ccs/bin/nm"
			LOADER="/bin/ld -E +s -Z"
			LIB_PATH=""
			INCLUDE_PATH="-D_HPUX_SOURCE -DSYSV -Dhpux"
			EXTRA_FTN_LIBS=
			EXTRA_LIBS="-lcl -lm"
			;;


	# HP platforms with older O/S:
	hppa* | hp700*)
			MAKE="/bin/make -f $MAKEFILE"
			SHLIB_EXT=sl
			C_COMPILER="/bin/cc -Aa -DMACHINE_HP"
			C_COMPLOAD="${C_COMPILER} -Wl,+s -Wl,-E -Wl,-Z"
			C_COMP_SHARED="${C_COMPILER} +z"
			C_OPTIONS="-g"
			FTN_COMPILER="/usr/bin/f77"
			FTN_COMPLOAD="${FTN_COMPILER} -Wl,+s"
			FTN_COMP_SHARED="${FTN_COMPILER}"
			LEX="/usr/bin/lex"
			LIB_ARCHIVE="/bin/ar cr"
			LIB_ORDER="/usr/bin/lorder"
			LIB_SORT="/usr/bin/tsort"
			LIB_SHARED="/bin/ld -b -E +s"
			LIB_NAMES="/bin/nm"
			LOADER="/bin/ld -E +s -Z"
			LIB_PATH=""
			INCLUDE_PATH="-D_HPUX_SOURCE -DSYSV -Dhpux"
			EXTRA_FTN_LIBS=
			EXTRA_LIBS="-lcl -lm"
			;;


	# SUN platforms:
	sun*2.7 | sun*2.6)
			MAKE="/usr/ccs/bin/make -f $MAKEFILE"
			SHLIB_EXT=so
			C_COMPILER="/opt/SUNWspro/bin/cc -Xc -DMACHINE_SUN"
			C_COMPLOAD="${C_COMPILER} -dy -xildoff"
			C_COMP_SHARED="${C_COMPILER} -Kpic"
			C_OPTIONS="-g"
			FTN_COMPILER="echo No FORTRAN"
			FTN_COMPLOAD="${FTN_COMPILER} -Wl,-dy"
			FTN_COMP_SHARED="${FTN_COMPILER} -fpic"
			LEX="/usr/ccs/bin/lex"
			LIB_ARCHIVE="/usr/ccs/bin/ar cr"
			LIB_ORDER="/fs_app/local/gnu/bin/lorder"
			LIB_SORT="/usr/ccs/bin/tsort"
			LIB_SHARED="/usr/ccs/bin/ld -dy -G"
			LIB_NAMES="/fs_app/local/gnu/bin/nm"
			LOADER="/usr/ccs/bin/ld -dy"
			LIB_PATH=""
			INCLUDE_PATH=""
			EXTRA_FTN_LIBS=
			EXTRA_LIBS="-lnsl -lgen -lm"
			;;


	# SUN platforms with older O/S:
	sun*)
			MAKE="/usr/ccs/bin/make -f $MAKEFILE"
			SHLIB_EXT=so
			C_COMPILER="/opt/SUNWspro/bin/cc -Xc -DMACHINE_SUN"
			C_COMPLOAD="${C_COMPILER} -dy -xildoff"
			C_COMP_SHARED="${C_COMPILER} -Kpic"
			C_OPTIONS="-g"
			FTN_COMPILER="echo No FORTRAN"
			FTN_COMPLOAD="${FTN_COMPILER} -Wl,-dy"
			FTN_COMP_SHARED="${FTN_COMPILER} -fpic"
			LEX="/usr/ccs/bin/lex"
			LIB_ARCHIVE="/usr/ccs/bin/ar cr"
			LIB_ORDER="/fs_app/local/gnu/bin/lorder"
			LIB_SORT="/usr/ccs/bin/tsort"
			LIB_SHARED="/usr/ccs/bin/ld -dy -G"
			LIB_NAMES="/fs_app/local/gnu/bin/nm"
			LOADER="/usr/ccs/bin/ld -dy"
			LIB_PATH=""
			INCLUDE_PATH=""
			EXTRA_FTN_LIBS=
			EXTRA_LIBS="-lnsl -lgen -lm"
			;;

	# LINUX on a PC:
	pcLinux*)
			MAKE="/usr/bin/make -f $MAKEFILE"
			SHLIB_EXT=so
			C_COMPILER="/usr/bin/gcc -ansi -fwritable-strings -DMACHINE_PCLINUX"
			C_COMPLOAD="${C_COMPILER} -Wl,-Bdynamic"
			C_COMP_SHARED="${C_COMPILER} -fPIC"
			C_OPTIONS="-g"
			FTN_COMPILER="/usr/bin/g77 -DMACHINE_PCLINUX"
			FTN_COMPLOAD="${FTN_COMPILER} -Wl,-Bdynamic"
			FTN_COMP_SHARED="${FTN_COMPILER} -fPIC"
			LIB_ORDER="/bin/echo"
			LIB_SORT="/usr/bin/sed 's///'"
			LIB_ARCHIVE="/usr/ccs/bin/ar cr"
			LIB_SHARED="/usr/bin/gcc -shared"
			LIB_NAMES="/usr/bin/nm"
			LOADER="/usr/bin/gcc"
			LIB_PATH=""
			INCLUDE_PATH="-D_SVID_SOURCE -D__USE_POSIX -D__USE_BSD"
			EXTRA_FTN_LIBS="-lg2c"
			EXTRA_LIBS="-lm -ltiff -lpng"
			;;


	*)		echo "Target Platform is Unknown"
			exit 1
			;;
esac
export MAKE
export SHLIB_EXT
export C_COMPILER C_COMPLOAD C_COMP_SHARED C_OPTIONS
export FTN_COMPILER FTN_COMPLOAD FTN_COMP_SHARED
export LEX
export LIB_ARCHIVE LIB_ORDER LIB_SORT LIB_SHARED LIB_NAMES
export LOADER
export LIB_PATH INCLUDE_PATH EXTRA_FTN_LIBS EXTRA_LIBS

# Set up non-platform-specific environment
export BINDIR;		BINDIR=$FPA/bin
export LIBDIR;		LIBDIR=$FPA/lib
export ULIBDIR;		ULIBDIR=$FPA/liblocal
export INCDIR;		INCDIR=$LIBDIR/include
export FPAHDR;		FPAHDR=$INCDIR/fpa.h
export TYPES;		TYPES=$INCDIR/fpa_types.h
export MACROS;		MACROS=$INCDIR/fpa_macros.h
export GETMEM;		GETMEM=$INCDIR/fpa_getmem.h
export MATH;		MATH=$INCDIR/fpa_math.h
export STRING;		STRING=$INCDIR/fpa_string.h
export TOOLS;		TOOLS=$LIBDIR/tools/tools.h
export OBJECTS;		OBJECTS=$LIBDIR/objects/objects.h
export ENVIRON;		ENVIRON=$LIBDIR/environ/environ.h
export EXTRACT;		EXTRACT=$LIBDIR/extract/extract.h
export FPALIB;		FPALIB=$LIBDIR/$PLATFORM/libfpa.$SHLIB_EXT
export FORTLIB;		FORTLIB=$LIBDIR/$PLATFORM/libfpafort.$SHLIB_EXT
export USRLIB;		USRLIB=$ULIBDIR/$PLATFORM/libfpauser.$SHLIB_EXT

if [ "$1" = "env" ]
then
	echo "Environment settings:"
	env
else
	target=${1:-"all"}
	eval "$MAKE $target" 2>&1 | tee log
fi
